Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 60, in <module>
    main()
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 56, in main
    time.sleep(REFRESH_SEC)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 60, in <module>
    main()
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 56, in main
    time.sleep(REFRESH_SEC)
KeyboardInterrupt
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
Traceback (most recent call last):
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\option_chain_worker.py", line 7, in <module>
    from crudeoil_option_live_mcx import (
  File "D:\Backup\CrudeOil_NSSM_New\backup_2025-07-02_12-31-24\crudeoil_option_live_mcx.py", line 6, in <module>
    import pandas as pd
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\__init__.py", line 61, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\core\api.py", line 1, in <module>
  File "C:\Users\rajiv\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
ImportError: DLL load failed while importing pandas_parser: Access is denied.
